// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/eduardogr/webser-go/internal/application/usecases/numbers"
	"github.com/eduardogr/webser-go/internal/framework/http"
	"github.com/eduardogr/webser-go/internal/framework/http/controllers/numbers"
	"github.com/eduardogr/webser-go/internal/framework/http/routes"
	"github.com/eduardogr/webser-go/internal/framework/storage/mysql"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeServer() (*http.Server, error) {
	statusRoute := routes.NewStatusRoute()
	db, err := mysql.SetupMysqlDatabase()
	if err != nil {
		return nil, err
	}
	numberRepository := mysql.NewMysqlNumberRepository(db)
	createNewNumberUsecase := usecases.NewCreateNumberUsecase(numberRepository)
	createNumberController := controllers.NewCreateNumberController(createNewNumberUsecase)
	getAllNumbersUsecase := usecases.NewGetAllNumbersUsecase(numberRepository)
	getAllNumbersController := controllers.NewGetAllNumbersController(getAllNumbersUsecase)
	getNumberByIdUsecase := usecases.NewGetNumberByIdUsecase(numberRepository)
	getNumberByIdController := controllers.NewGetNumberByIdController(getNumberByIdUsecase)
	updateNumberByIdUsecase := usecases.NewUpdateNumberByIdUsecase(numberRepository)
	updateNumberByIdController := controllers.NewUpdateNumberByIdController(updateNumberByIdUsecase)
	removeNumberByIdUsecase := usecases.NewRemoveNumberByIdUsecase(numberRepository)
	removeNumberByIdController := controllers.NewRemoveNumberByIdController(removeNumberByIdUsecase)
	numbersRoute := routes.NewNumbersRoute(createNumberController, getAllNumbersController, getNumberByIdController, updateNumberByIdController, removeNumberByIdController)
	routerBuilder := routes.NewRouterBuilder(statusRoute, numbersRoute)
	server := http.NewServer(routerBuilder)
	return server, nil
}

// wire.go:

var NumberRouteControllersSet = wire.NewSet(controllers.NewCreateNumberController, controllers.NewGetAllNumbersController, controllers.NewGetNumberByIdController, controllers.NewUpdateNumberByIdController, controllers.NewRemoveNumberByIdController)

var UseCasesSet = wire.NewSet(usecases.NewCreateNumberUsecase, usecases.NewGetAllNumbersUsecase, usecases.NewGetNumberByIdUsecase, usecases.NewUpdateNumberByIdUsecase, usecases.NewRemoveNumberByIdUsecase)
