// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/eduardogr/webser-go/pkg/api"
	"github.com/eduardogr/webser-go/pkg/repository"
	"github.com/eduardogr/webser-go/pkg/server"
)

// Injectors from wire.go:

func InitializeServer() (*server.Server, error) {
	db, err := repository.SetupDatabase()
	if err != nil {
		return nil, err
	}
	storage := repository.NewStorage(db)
	numberRepository := repository.ProvideNumberRepository(storage)
	numberService := api.NewNumberService(numberRepository)
	handler := server.NewHandler(numberService)
	router := server.NewRouter(handler)
	serverServer := server.NewServer(router)
	return serverServer, nil
}
